### ISSUE TITLE
Error: Provider produced inconsistent final plan when changing the contact email address

### ISSUE THREAD

**Issue by siwyd** [akamai/terraform-provider-akamai#176] opened 2020-07-30 08:20 UTC
### Terraform Version
Terraform v0.12.28
Akamai v0.8.0

### Affected Resource(s)
- akamai_property
- akamai_property_activation

### Terraform Configuration Files
Happened to me when the only change was changing the contact on both the property and property activation.

### Expected Behavior
Apply should not fail.

### Actual Behavior
The plan works but the apply fails:

```
10:02:24  Error: Provider produced inconsistent final plan
10:02:24  
10:02:24  When expanding the plan for akamai_property_activation.dsa_lfvp_web to include
10:02:24  new values learned so far during apply, provider
10:02:24  "registry.terraform.io/-/akamai" produced an invalid new value for .version:
10:02:24  was cty.NumberIntVal(2), but now cty.NumberIntVal(3).
10:02:24  
10:02:24  This is a bug in the provider, which should be reported in the provider's own
10:02:24  issue tracker.
10:02:24  
```

### Important Factoids
After the first apply, the second apply then works and all is well again.

**Comment by siwyd** [comment] 2020-07-31 12:11
I only just got this behavior when changing an activation from STAGING to PRODUCTION:
```
~ network  = "STAGING" -> "PRODUCTION"
```

**Comment by zstlaw** [comment] 2020-12-14 19:16
Thanks for reporting this issue. We are not able to reproduce this issue with our latest release. With 1.0.0, provider code has been significantly revamped and many issues were addressed. Please try upgrading to 1.0.0 and if you still face issues, Please let us know. 

Please refer https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/1.0_migration for details relating to to 1.0.0 migration.

If you encounter an issue retesting this scenario with 1.0.0 release, please submit a new issue.

Closing this issue.

**Closed as completed by zstlaw** 2020-12-14 19:16 UTC
