### ISSUE TITLE
Does TF supports API V3?

### ISSUE THREAD

**Issue by smoraboi** [akamai/terraform-provider-akamai#449] opened 2023-07-17 10:15 UTC
Hi Team,

Trying to fetch shared cloudlet policies using TF, but TF can't able to fetch it, it doesn't seems to identify the policies in the account? It gives below error. However when i try to fetch individual policy from another account, i can able to do it.
**Error exporting policy HCL: unable to fetch policy with given name: policy 'example_policy' does not exist.**

When checking API documents for cloudlets, it says shared policies are accessed by API V3 endpoints, Is this the limitation TF has, hence not able to fetch the shared policies?

**Comment by mimazaka** [comment] 2023-07-19 06:50
Hello @smoraboi ,
At this moment we supports only API V2 for cloudlets, and adding support for cloudlets V3 is on our roadmap.

**Comment by lkowalsk-akamai-com** [comment] 2023-07-20 11:46
Hi @smoraboi, I will close this ticket as a duplicate of this one https://github.com/akamai/terraform-provider-akamai/issues/276

**Closed as completed by lkowalsk-akamai-com** 2023-07-20 11:46 UTC
