### ISSUE TITLE
DXE-2915 Validation for `destination_path_other` incorrect?

### ISSUE THREAD

**Issue by oliversalzburg** [akamai/terraform-provider-akamai#452] opened 2023-07-21 14:01 UTC
### Terraform Version
Terraform v1.5.2

### Affected Resource(s)
- akamai_property_rules_builder (v3.6.0)

### Terraform Configuration Files
```hcl
data "akamai_property_rules_builder" "redirect_strip_trailing_slash" {
  rules_v2023_01_05 {
    behavior {
      redirect {
        destination_hostname   = "SAME_AS_REQUEST"
        destination_path       = "OTHER"
        destination_path_other = "{{user.PMUSER_REDIRECT_PATH}}"
        destination_protocol   = "SAME_AS_REQUEST"
        mobile_default_choice  = "DEFAULT"
        query_string           = "APPEND"
        response_code          = 302
      }
    }
  }
}
```

### Expected Behavior
The variable is accepted as the path.

### Actual Behavior
```
│ Error: value destination_path_other: "{{user.PMUSER_REDIRECT_PATH}}" does not match the pattern "^/"
│ 
│   with module.akamai.module.rules.data.akamai_property_rules_builder.redirect_strip_trailing_slash,
│   on ../../terraform/modules/akamai-edge/akamai-sites-rules/main.tf line 441, in data "akamai_property_rules_builder" "redirect_strip_trailing_slash":
│  441:         destination_path_other = "{{user.PMUSER_REDIRECT_PATH}}"
│ 
╵
```

This works fine when authoring via the web UI, and when using a JSON template (`"destinationPathOther": "{{user.PMUSER_REDIRECT_PATH}}"`).

I wasn't able to verify if this is fixed with the latest version, because we experience other issues with later versions of the provider, which is why I'm trying to use `akamai_property_rules_builder` in the first place.

**Comment by oliversalzburg** [comment] 2023-07-24 12:56
Confirmed that this is still the case in 5.0.1

**Comment by dawiddzhafarov** [comment] 2023-07-25 07:16
Hi @oliversalzburg, thank You for opening the issue.

I can confirm that the issue is still valid in the newest version. The fix for the problem will be in the upcoming release.

Kind regards,
Dawid

**Comment by lkowalsk-akamai-com** [comment] 2023-08-01 13:06
This is fixed now in recent release.

**Closed as completed by lkowalsk-akamai-com** 2023-08-01 13:06 UTC
Labels: released
