### ISSUE TITLE
akamai_dns_zone resource requires mandatory MASTERS argument, even when creating a Primary Fast DNS zone

### ISSUE THREAD

**Issue by ghost** [akamai/terraform-provider-akamai#61] opened 2019-10-10 18:50 UTC
When creating a new Fast DNS zone with Terraform, you use the akamai_dns_zone resource. This resource has a mandatory use of the MASTERS arguments, the Master Nameservers are only needed for Secondary Fast DNS. When using Primary Fast DNS, there are no nameservers needed as these are Akamai's nameservers.

Masters should only be required when type ="secondary".

### Terraform Version
Terraform v0.12.10
+ provider.akamai v0.1.3
+ provider.local v1.4.0

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_dns_zone

### Terraform Configuration Files
resource "akamai_dns_zone" "schrodingerstudios" {
    contract = "${data.akamai_contract.default.id}"
    group = "${data.akamai_group.default.id}"

    zone = "schrodingerstudios.com"
    type =  "primary"
    masters = [
      "1.2.3.4"
    ] 

    comment =  "Using Terraform to manage DNS"
    sign_and_serve = false
    
}

### Debug Output
Error: Missing required argument

  on akamai.tf line 26, in resource "akamai_dns_zone" "schrodingerstudios":
  26: resource "akamai_dns_zone" "schrodingerstudios" {

The argument "masters" is required, but no definition was found.

### Important Factoids
Adding the masters with fake nameservers will work, when defining a primary zone, this information is not ported to Akamai Fast DNS API. So it can work by adding fake data, but not user friendly and confusing.

**Comment by martinstibbe** [comment] 2019-10-30 19:20
Identified the root cause for this issue and this is fixed in PR: #70

**Comment by martinstibbe** [comment] 2019-12-07 19:47
https://releases.hashicorp.com/terraform-provider-akamai/0.1.4/ released please test and validate

**Closed as completed** 2019-12-19 19:20 UTC
