### ISSUE TITLE
feat: Akamai Site Shield data sources

### ISSUE THREAD

**Issue by srgustafson8** [akamai/terraform-provider-akamai#458] opened 2023-08-10 09:41 UTC
We are automating Akamai property creation and having it point at resources in our cloud environments. We'd like to ensure only traffic routed from the correct location, and so want to include our Site Shield IPs in our firewall rules, but lack any Terraform resource for retrieving these.

This may actually be present but I can't easily navigate the Techdocs documentation and docs were removed from the Terraform registry. 

API Docs: 
- https://techdocs.akamai.com/site-shield/reference/get-maps
- https://techdocs.akamai.com/site-shield/reference/get-map

An example of what i'd expect to see once implemented. 

```hcl
data "akamai_site_shield_maps" "this" {} # List Maps API resource

data "akamai_site_shield_map" "this" { # Get Map API resource
  id = data.akamai_site_shield_maps.this[0].id
}

resource "a_waf_rule" "this" {
...
  rule {
    action = "ALLOW"
    ip_range = data.akamai_site_shield_map.this.current_cidrs
  }
}
```

**Comment by lkowalsk-akamai-com** [comment] 2023-08-10 11:10
In order to keep things clean, I'm closing this ticket as a duplicate of this one: https://github.com/akamai/terraform-provider-akamai/issues/227. All status updates will be done in the mentioned ticket.

**Closed as completed by lkowalsk-akamai-com** 2023-08-10 11:10 UTC
