### ISSUE TITLE
DXE-3477 Error when activating property configuration changes - Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by akrrev** [akamai/terraform-provider-akamai#549] opened 2024-04-24 13:27 UTC
Hi,

I experience a bug when I try to update the configurations for multiple properties. The error mentions an inconsistent final plan, which should be a provider issue and seems to be caused in the property activation, even when I'm not activating a new version.

### Terraform and Akamai Terraform Provider Versions
```sh
Terraform v1.8.1
on darwin_arm64
+ provider registry.terraform.io/akamai/akamai v6.1.0
+ provider registry.terraform.io/hashicorp/local v2.5.1
+ provider registry.terraform.io/hashicorp/time v0.11.1
+ provider registry.terraform.io/hashicorp/tls v4.0.5
```

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_property_activation
- akamai_property (not sure if it directly relates to the property or only the property activation).

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    akamai = {
      source  = "akamai/akamai"
      version = ">= 6.1.0"
    }
  }
  required_version = ">= 1.8.1"
}

locals {
  hostname_list = flatten([
    ... # for loop generating desired structure for dynamic "hostnames" block.
  ])
}

provider "akamai" {
  edgerc         = "edgerc-location"
  config_section = "config-section"
}

resource "akamai_edge_hostname" "PROPERTY_NAME-edgekey-net" {
  contract_id   = "contract-id"
  group_id      = "group-id"
  ip_behavior   = "IPV6_COMPLIANCE"
  edge_hostname = "PROPERTY_NAME.edgekey.net"
}

resource "akamai_property" "PROPERTY_NAME" {
  name      = "PROPERTY_NAME"
  contract_id = "contract_id"
  group_id = "group-id"
  product_id = "prd_Site_Accel"
  hostnames {
    cname_from             = "HOSTNAME"
    cname_to               = akamai_edge_hostname.PROPERTY_NAME-edgekey-net.edge_hostname
    cert_provisioning_type = "CPS_MANAGED"
  }
  dynamic "hostnames" {
    for_each = local.hostname_list
    content {
      cname_from             = "${hostnames.value.hostname}.MORE"
      cname_to               = akamai_edge_hostname.PROPERTY_NAME-edgekey-net.edge_hostname
      cert_provisioning_type = "CPS_MANAGED"
    }
  }
  rule_format = data.akamai_property_rules_builder.PROPERTY_NAME_rule_default.rule_format      # v2024_01_09
  rules       = data.akamai_property_rules_builder.PROPERTY_NAME_rule_default.json
}

resource "akamai_property_activation" "PROPERTY_NAME-staging" {
  property_id                    = akamai_property.PROPERTY_NAME.id
  contact                        = ["contact1@example.com", "contact2@example.com"]
  version                        = var.activate_stage ? akamai_property.PROPERTY_NAME.latest_version : akamai_property.PROPERTY_NAME.staging_version
  network                        = "STAGING"
  auto_acknowledge_rule_warnings = false
  # note                           = ""
}

resource "akamai_property_activation" "PROPERTY_NAME-production" {
  property_id                    = akamai_property.PROPERTY_NAME.id
  contact                        = ["contact1@example.com", "contact2@example.com"]
  version                        = var.activate_prod ? akamai_property.PROPERTY_NAME.latest_version : akamai_property.PROPERTY_NAME.production_version
  network                        = "PRODUCTION"
  auto_acknowledge_rule_warnings = false
  # note                           = ""
}
```

### Expected Behavior
The provider should have updated my properties and activations with the latest configurations and note(s).

### Actual Behavior
```
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for akamai_property_activation.PROPERTY_NAME-staging to include new values learned so far during apply, provider "registry.terraform.io/akamai/akamai"
│ produced an invalid new value for .note: was null, but now cty.StringVal("SOME COMMENT").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for akamai_property_activation.PROPERTY_NAME-production to include new values learned so far during apply, provider "registry.terraform.io/akamai/akamai"
│ produced an invalid new value for .note: was null, but now cty.StringVal("SOME COMMENT").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Steps to Reproduce
1. Implement changes to the property configuration or its rules.
2. Leave `auto_acknowledge_rule_warnings` as false
3. Change or remove the note for the property activation
4. Run `terraform apply`

### Additional info
I experienced the same issues in Terraform version 1.6.2 with Akamai Provider version 6.0.0

**Comment by lsadlon** [comment] 2024-04-24 13:53
Hi @akrrev 

Thanks for reporting this issue. We were able to reproduce it and will inform you about the progress of fix.

BR,
Lukasz

**Comment by chouraamine** [comment] 2024-05-27 16:03
Hi @lsadlon,

Any update about this issue please ? 

Regards,

**Comment by lkowalsk-akamai-com** [comment] 2024-05-28 15:54
Hi @chouraamine, this issue is going to be addressed in one of the comming releases. We cannot provide the date just yet.

**Comment by chouraamine** [comment] 2024-06-11 15:21
Same issue on different Akamai version ... the JSON files of the rules are generated from .tmpl files 
files, for example : 

**// main.tf**
```
resource "local_file" "default" {
  content = templatefile("${path.module}/rule_templates/default.tmpl",
    {
      "origin_endpoint" = var.origin_endpoint
      "cp_code_id"      = local.akamai_cp_code

    }
  )
  filename = "${path.module}/property-snippets/default.json"

}
```

**//default.tmpl**

```
{
    "rules": {
      "name": "default",
      "behaviors": [
        {
            "name": "origin",
            "options": {
                "originType": "CUSTOMER",
                "hostname": "${origin_endpoint}",
                "forwardHostHeader": "REQUEST_HOST_HEADER",
                "cacheKeyHostname": "ORIGIN_HOSTNAME",
                "compress": true,
                "enableTrueClientIp": true,
                "originCertificate": "",
                "verificationMode": "CUSTOM",
                "ports": "",
                "httpPort": 80,
                "httpsPort": 443,
                "originSni": true,
                "trueClientIpHeader": "True-Client-IP",
                "trueClientIpClientSetting": false,
                "customValidCnValues": [
                    "{{Origin Hostname}}",
                    "{{Forward Host Header}}"
                ],
                    "originCertsToHonor": "COMBO",
                    "standardCertificateAuthorities": [
                        "akamai-permissive"
                    ],
                    "ipVersion": "IPV4",
                    "customCertificateAuthorities": [
                        {
                            "subjectCN": "LPL Technical CA",
                            "subjectAlternativeNames": [],
                            "subjectRDNs": {
                                "C": "FR",
                                "CN": "LPL Technical CA",
                                "O": "CHANEL"
                            },
                            "issuerRDNs": {
                                "C": "FR",
                                "CN": "LPL Root CA",
                                "O": "CHANEL"
                            },
                            "notBefore": 1591362027000,
                            "notAfter": 2380280427000,
                            "sigAlgName": "SHA256WITHRSA",
                            "publicKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                            "publicKeyAlgorithm": "RSA",
                            "publicKeyFormat": "X.509",
                            "serialNumber": "XXXXXXXXXXXXXXXXXXXXXX",
                            "version": 3,
                            "sha1Fingerprint": "XXXXXXXXXXXXXXXXXXXXx",
                            "pemEncodedCert": "-----BEGIN CERTIFICATE-----XXXXXXXXXXXXXXXXXX",
                            "canBeLeaf": false,
                            "canBeCA": true,
                            "selfSigned": false
                        },
                        {
                            "subjectCN": "LPL Root CA",
                            "subjectAlternativeNames": [],
                            "subjectRDNs": {
                                "C": "FR",
                                "CN": "LPL Root CA",
                                "O": "CHANEL"
                            },
                            "issuerRDNs": {
                                "C": "FR",
                                "CN": "LPL Root CA",
                                "O": "CHANEL"
                            },
                            "notBefore": 1591357245000,
                            "notAfter": 2538042045000,
                            "sigAlgName": "SHA256WITHRSA",
                            "publicKey": "XXXXXXXXXXXXXXX",
                            "publicKeyAlgorithm": "RSA",
                            "publicKeyFormat": "X.509",
                            "serialNumber": "XXXXXXXXXXXXXXXXX",
                            "version": 3,
                            "sha1Fingerprint": "XXXXXXXXXXXXXXXXXXXXXX",
                            "pemEncodedCert": "-----BEGIN CERTIFICATE-----XXXXXXXXXX==\n-----END CERTIFICATE-----\n",
                            "canBeLeaf": false,
                            "canBeCA": true,
                            "selfSigned": true
                        }
                    ],
                    "customCertificates": []
                }
            },
        {
            "name": "caching",
            "options": {
                "behavior": "MAX_AGE",
                "mustRevalidate": false,
                "ttl": "7d"
            }
        }, 
      {
        "name": "cpCode",
        "options": {
          "value": {
            "id": ${cp_code_id}
          }
        }
      }
      ],
      "options": {
        "is_secure": true
      },
      "variables": [
      ],
      "comments": "The behaviors in the Default Rule apply to all requests for the property hostname(s) unless another rule overrides the Default Rule settings.",
  
  
      "children": [
        "#include:global_performance.json",
        "#include:global_offload.json",
        "#include:security_hardening.json",
        "#include:http_methods.json",
        "#include:datastream.json"
      ]
    }
  
   
  }
```

**Comment by DhroovP** [comment] 2024-07-01 21:25
Hi there, I seem to be facing a related issue though it might be different enough to warrant it's own separate issue (let me know if I should create a new one). When adding a note to a property  activation resource that did not previously have one, I'm getting the following error message:

`│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ akamai_property_activation.property[0] to
│ include new values learned so far during apply, provider
│ "registry.terraform.io/akamai/akamai" produced an invalid new value for
│ .note: was cty.StringVal("NEW NOTE"), but now cty.StringVal("").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.`

This also happens when we try to get rid of the note parameter completely (but the error is slightly different) or when we try to keep one consistent note across all of our property activations. Not sure what to do about this, seems to be an issue in our pipelines and it's a total blocker at the moment.

We are using akamai/akamai 6.2.0 & Terraform 1.6.6.

**Comment by mgwoj** [comment] 2024-07-19 07:21
Hello @akrrev, this issue should be fixed in the recent release.

**Closed as completed by mgwoj** 2024-07-19 07:21 UTC
Labels: bug, delivery

**Comment by akrrev** [comment] 2024-09-02 13:48
Thanks, @mgwoj - I just tested it and it works!
