### ISSUE TITLE
DXE-2221 MTLS Settings not working

### ISSUE THREAD

**Issue by dmoreira-sbp** [akamai/terraform-provider-akamai#339] opened 2022-08-31 09:41 UTC
### The problem

When adding MTLS settings to the dv_enrollment resource, we get an "Invalid network configuration - Create enrollment request contains client mutual authentication configuration" message.

### Terraform Version
Terraform version: 1.2.2
Akamai provider: 2.2.0

### Affected Resource(s)
- akamai_cps_dv_enrollment

### Terraform Configuration Files
```hcl
resource "akamai_cps_dv_enrollment" "certificate" {
acknowledge_pre_verification_warnings = true
certificate_chain_type                = "default"
common_name                           = "redacted.net"
contract_id                           = "ctr_1-ABCDEF"
dns_challenges                        = [
    {
        domain        = "www.redacted.net"
            },
        ]
enable_multi_stacked_certificates     = false
http_challenges                       = [
    {
        domain        = "www.redacted.net"
           },
        ]
sans                                  = [
    "redacted.net",
        ]
secure_network                        = "enhanced-tls"
signature_algorithm                   = "SHA-256"
sni_only                              = true
 
admin_contact {
    address_line_one = "Redacted"
    city             = "Redacted"
    country_code     = "RD"
    email            = "redacted@topsecret.com"
    first_name       = "Redacted"
    last_name        = "Redacted"
    organization     = "Redacted"
    phone            = "+31123456789"
    postal_code      = "1111PP"
    region           = "Redacted"
    title            = "Administrator"
        }
 
csr {
    city         = "Redacted"
    country_code = "RD"
    organization = "Redacted"
    state        = "Redacted"
        }
 
network_configuration {
    clone_dns_names         = false
    disallowed_tls_versions = [
        "TLSv1",
        "TLSv1_1",
        "TLSv1_2",
            ]
    geography               = "core"
    must_have_ciphers       = "ak-akamai-2020q1"
    ocsp_stapling           = "on"
    preferred_ciphers       = "ak-akamai-2020q1"
    quic_enabled            = false
 
    client_mutual_authentication {
        ocsp_enabled           = true
        send_ca_list_to_client = false
        set_id                 = "12345"
            }
        }
 
organization {
    address_line_one = "Redacted"
    city             = "Redacted"
    country_code     = "RD"
    name             = "Redacted"
    phone            = "+31123456789"
    postal_code      = "1111PP"
    region           = "Redacted"
        }
 
tech_contact {
    address_line_one = "150 Broadway"
    city             = "Cambridge"
    country_code     = "US"
    email            = "redacted@akamai.com"
    first_name       = "Redacted"
    last_name        = "Redacted"
    organization     = "Akamai"
    phone            = "+919123123234"
    postal_code      = "12345"
    region           = "MA"
    title            = "Administrator"
        }
    }

```

### Debug Output
```
│ Error: create enrollment: API error: 
│ {
│       "type": "Bad Request",
│       "title": "Invalid network configuration.",
│       "detail": "Create enrollment request contains client mutual authentication configuration.",
│       "statusCode": 400
│ }
│ 
│   with module.property.akamai_cps_dv_enrollment.certificate,
│   on ../../provider/akamai/03_certificates.tf line 1, in resource "akamai_cps_dv_enrollment" "certificate":
│    1: resource "akamai_cps_dv_enrollment" "certificate" {
```

### Expected Behavior
Adding MTLS settings to the configuration

### Actual Behavior
Configuration is rejected due to it including MTLS configuration

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by wzagrajcz** [comment] 2022-09-02 11:56
Hello @dmoreira-sbp,
Thank You for reporting this issue. We will investigate what is happening and come back to You.

Best Regards,
Wojciech

**Comment by RemcoAA** [comment] 2022-09-08 11:53
Hi, is there any update to report? This code worked at the beginning of July but is now generating errors.

**Comment by wzagrajcz** [comment] 2022-09-08 13:18
Hello,
It turned out that the issue is not on terraform-provider side. The same issue occurs when using a product API directly (e.g. using Postman).
Asked that product team about it and they suggested that something is incorrect in configuration. Is the value of setId correct? The CA set has to be created and deployed before creating an enrolment (using Trust Chain Manager - to use which use needs special Tech Preview product added in contract).

Hope that helps.

Best Regards,
Wojciech

**Comment by RemcoAA** [comment] 2022-09-08 14:09
Hi we tried again today with the same setId (for a CA set that was already created) and now we are not getting errors.

The other confusing issue is that in the API documentation it is mentioned the setId should be an xml file (like "Custom_abcd_1-xxxxx.xml") but in Terraform this needs to be a 5-digit Integer.
Is there more information on the setId value when using Terraform?

**Comment by mgwoj** [comment] 2022-09-09 15:25
Regarding `setId` field, it is the name of the CA set that must exist and be deployed to both Staging and production in TCM (and there is no "Custom_" prefix included).
We will correct the documentation to resolve this confusion with prefix.

Do you have any more questions regarding this topic or can we close it?

**Comment by RemcoAA** [comment] 2022-11-28 12:30
Hi,

our Terraform code has been working for awhile but now the issue is back again.


│ Error: create enrollment: API error:
│ {│       "type": "Bad Request",│       "title": "Invalid network configuration.",│       "detail": "Create enrollment request contains client mutual authentication configuration.",│       "statusCode": 400

Also via the API I am getting the same error.

Can you please check again.

**Comment by lkowalsk-akamai-com** [comment] 2023-07-28 13:32
This issue was fixed in the recent release.

**Closed as completed by lkowalsk-akamai-com** 2023-07-28 13:32 UTC
Labels: bug, planned
