### ISSUE TITLE
Array values in var_definition_file lead to malformed json

### ISSUE THREAD

**Issue by netzding** [akamai/terraform-provider-akamai#278] opened 2022-01-21 14:21 UTC
### Terraform Version
Terraform version: 1.1.0

### Affected Resource(s)
- akamai_property_rules_template

### Terraform Configuration Files
```hcl
data "akamai_property_rules_template" "akarules" {
  template_file       = abspath("${path.root}/array_test/property-snippets/main.json")
  var_definition_file = abspath("${path.root}/array_test/variableDefinitions.json")
  var_values_file     = abspath("${path.root}/array_test/variables.json")
}
```
### Snippets/main.json
```json
{
    "rules": {
        "name": "default",
        "children": [],
        "behaviors": [
            {
                "name": "origin",
                "options": {
                    "cacheKeyHostname": "REQUEST_HOST_HEADER",
                    "compress": true,
                    "enableTrueClientIp": true,
                    "forwardHostHeader": "REQUEST_HOST_HEADER",
                    "httpPort": 80,
                    "originType": "CUSTOMER",
                    "hostname": "${env.originHostname}",
                    "trueClientIpHeader": "True-Client-IP",
                    "trueClientIpClientSetting": false,
                    "verificationMode": "CUSTOM",
                    "originSni": true,
                    "httpsPort": 443,
                    "originCertificate": "",
                    "ports": "",
                    "customValidCnValues": "${env.originCnName}",
                    "originCertsToHonor": "STANDARD_CERTIFICATE_AUTHORITIES",
                    "standardCertificateAuthorities": [
                        "akamai-permissive"
                    ]
                }
            },
            {
                "name": "cpCode",
                "options": {
                    "value": {
                        "id": "${env.cpCode}"
                    }
                }
            },
            {
                "name": "caching",
                "options": {
                    "behavior": "CACHE_CONTROL_AND_EXPIRES",
                    "mustRevalidate": false,
                    "defaultTtl": "3m",
                    "honorPrivateEnabled": false,
                    "honorMustrevalidateEnabled": false
                }
            },
            {
                "name": "allowPost",
                "options": {
                    "allowWithoutContentLength": false,
                    "enabled": true
                }
            },
            {
                "name": "tieredDistribution",
                "options": {
                    "enabled": true
                }
            },
            {
                "name": "http2",
                "options": {
                    "enabled": ""
                }
            },
            {
                "name": "allowTransferEncoding",
                "options": {
                    "enabled": true
                }
            },
            {
                "name": "cacheTagVisible",
                "options": {
                    "behavior": "PRAGMA_HEADER"
                }
            }
        ],
        "options": {
            "is_secure": true
        },
        "variables": [],
        "comments": "Just a test"
    }
}
```
### variableDefinitions.json
```json
{
    "definitions": {
        "originHostname": {
            "type": "hostname",
            "default": null
        },
        "originCnName": {
            "type": "array",
            "default": null
        },
        "cpCode": {
            "type": "cpCode",
            "default": null
        }
    }
}
```
### variables.json
```json
{
    "originHostname": "example.com",
    "originCnName": [ "origin.example.com",
                      "stage.origin.example.com",
                      "{{Origin Hostname}}",
                      "{{Forward Host Header}}"
                    ],
    "cpCode": 123456
}

```
### Debug Output
https://gist.github.com/netzding/82ec455ffc3b7ddfe2f4de672b232de3#file-gistfile1-txt-L507
(relevant line 507 is highlighted)

### Expected Behavior
A valid json should be generated

### Actual Behavior
Malformed json is being generated (array values are not being properly quoted)

### Steps to Reproduce
1. `terraform plan`

### Workaround
If you include quotes and commas in the actual array values you can generate a valid json:
```json
{
    "originHostname": "example.com",
    "originCnName": [ "\"origin.example.com\",",
                      "\"stage.origin.example.com\",",
                      "\"{{Origin Hostname}}\",",
                      "\"{{Forward Host Header}}\""
                    ],
    "cpCode": 123456
}
```

### References
Related to:
- GH-257

**Comment by lkowalsk-akamai-com** [comment] 2022-01-27 20:21
Hi @netzding,
This issue should have been resolved within latestes Akamai Terraform Provider release. I'm closing this ticket, please reopen if the issue is still there.

**Closed as completed by lkowalsk-akamai-com** 2022-01-27 20:21 UTC
