### ISSUE TITLE
DXE-3993 data.akamai_cps_csr returns could not get enrollment: fetching enrollment: request failed: unexpected EOF

### ISSUE THREAD

**Issue by landrew57** [akamai/terraform-provider-akamai#562] opened 2024-06-24 09:40 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform and Akamai Terraform Provider Versions

```
$ terraform -v
Terraform v1.8.5
on darwin_arm64
+ provider registry.terraform.io/akamai/akamai v6.2.0
```

### Affected Resource(s)

- data.akamai_cps_csr 

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "akamai" {
  edgerc         = "~/.edgerc"
  config_section = "test"
}

data "akamai_cps_csr" "example" {
  enrollment_id = 82838
}

terraform {
  required_providers {
    akamai = {
      source  = "akamai/akamai"
      version = "6.2.0"
    }
  }
  required_version = ">= 1.0"
}
```

### Debug Output
https://gist.github.com/landrew57/d83e17ddf1da4c70523ba714107e153e

### Expected Behavior

A CSR should be returned

### Actual Behavior

```
$ terraform plan
data.akamai_cps_csr.example: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: could not get enrollment: fetching enrollment: request failed: unexpected EOF
│
│   with data.akamai_cps_csr.example,
│   on main.tf line 6, in data "akamai_cps_csr" "example":
│    6: data "akamai_cps_csr" "example" {
│
╵
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by lsadlon** [comment] 2024-06-24 10:47
Hi @landrew57,

Thanks for reporting this issue. Could you verify if you get correct response trying to get enrollment (https://techdocs.akamai.com/cps/reference/get-enrollment) with some other tool, like postman? 

BR,
Lukasz

**Comment by landrew57** [comment] 2024-06-24 11:16
Hi @lsadlon, thanks for the prompt response!

I don't know what the correct response looks like, but by using httpie and doing

```bash
$ http :/cps/v2/enrollments/82838 'accept: application/vnd.akamai.cps.enrollment.v11+json' --auth-type edgegrid -a test:
```

With some values removed but all the keys present I get

```json
{
    "adminContact": {
        "addressLineOne": null,
        "addressLineTwo": null,
        "city": null,
        "country": null,
        "email": "joe.bloggs@example.uk",
        "firstName": "joe",
        "lastName": "bloggs",
        "organizationName": null,
        "phone": "0123456890",
        "postalCode": null,
        "region": null,
        "title": null
    },
    "assignedSlots": [
        <slot>
    ],
    "autoRenewalStartTime": null,
    "certificateChainType": "default",
    "certificateType": "third-party",
    "changeManagement": true,
    "csr": {
        "c": "",
        "cn": "",
        "l": "",
        "o": "",
        "ou": null,
        "preferredTrustChain": null,
        "sans": [],
        "st": ""
    },
    "enableMultiStackedCertificates": true,
    "id": 82838,
    "location": "/cps/v2/enrollments/82838",
    "maxAllowedSanNames": 100,
    "maxAllowedWildcardSanNames": 100,
    "networkConfiguration": {
        "clientMutualAuthentication": {
            "authenticationOptions": {
                "ocsp": {
                    "enabled": false
                },
                "sendCaListToClient": true
            },
            "setId": null
        },
        "disallowedTlsVersions": [],
        "dnsNameSettings": {
            "cloneDnsNames": true,
            "dnsNames": []
        },
        "geography": "core",
        "mustHaveCiphers": "",
        "ocspStapling": "on",
        "preferredCiphers": "",
        "quicEnabled": false,
        "secureNetwork": "standard-tls",
        "sniOnly": true
    },
    "org": {
        "addressLineOne": "",
        "addressLineTwo": null,
        "city": "",
        "country": "",
        "name": "",
        "phone": "",
        "postalCode": "",
        "region": ""
    },
    "orgId": null,
    "pendingChanges": [
        {
            "changeType": "renewal",
            "location": "/cps/v2/enrollments/82838/changes/5111866"
        }
    ],
    "productionSlots": [
        42769
    ],
    "ra": "third-party",
    "signatureAlgorithm": null,
    "stagingSlots": [
        42769
    ],
    "techContact": {
        "addressLineOne": null,
        "addressLineTwo": null,
        "city": null,
        "country": null,
        "email": "",
        "firstName": "",
        "lastName": "",
        "organizationName": null,
        "phone": "",
        "postalCode": null,
        "region": null,
        "title": null
    },
    "thirdParty": {
        "excludeSans": false
    },
    "validationType": "third-party"
}
```

**Comment by lsadlon** [comment] 2024-06-24 12:12
Hi @landrew57,

Thanks for additional info. We will investigate it and go back to you.

BR,
Lukasz

**Comment by landrew57** [comment] 2024-06-24 16:19
We have an open support case in which I have linked to this issue: [F-CS-8578308](https://control.akamai.com/apps/case-management/#/cases/F-CS-8578308/view).

**Comment by landrew57** [comment] 2024-06-26 09:28
In that case Akamai pointed out that the enrollment id being used had mTLS enabled. When we tested with an enrollment that does not have mTLS enabled we did not see the issue.

**Comment by hypnotisttom** [comment] 2024-07-09 18:23
We are having the same issue too, and the only difference between our working and non-working ones are the presence of the mTLS block.

This is happening for both import and plan/apply.

I suspect there could be a greedy regex in the getter.

Just wanted to add this comment so that you know we also have the exact same behavior.

**Comment by dawiddzhafarov** [comment] 2024-07-10 08:05
Hello,

Correct, enrollments that have mTLS enabled are affected. As soon as the issue is fixed, it should start working in Terraform Provider and any other tools. 

With regards,
Dawid

**Comment by dawiddzhafarov** [comment] 2024-07-18 07:05
Hi all,

Can you please verify if the issue still persists?

With regards,
Dawid

**Comment by hypnotisttom** [comment] 2024-07-18 19:28
> Hi all,
> 
> Can you please verify if the issue still persists?
> 
> With regards, Dawid

HI @dawiddzhafarov,

As of July 9th it existed, which is when we last tested. Is there a new version we should test against, or are you attempting to reproduce it?

**Comment by dawiddzhafarov** [comment] 2024-07-19 06:28
Hello,

The fix for that issue was shipped around 16th of July. No new version of Terraform Provider is required as the issue was not caused by it and the fix is transparent for Terraform users.

With regards,
Dawid

**Comment by hypnotisttom** [comment] 2024-07-19 16:29
> Hello,
> 
> The fix for that issue was shipped around 16th of July. No new version of Terraform Provider is required as the issue was not caused by it and the fix is transparent for Terraform users.
> 
> With regards, Dawid

@dawiddzhafarov

Ah, the team confirms with some preliminary testing that it looks good now. We will continue testing just to be sure. 

Can you confirm this was a backend API fix?

**Comment by dawiddzhafarov** [comment] 2024-07-22 06:05
Hi,

Yes, the issue originated from the backend API, hence the fix does not require new TFP release.

With regards,
Dawid

**Comment by wzagrajcz** [comment] 2024-07-22 08:15
Hello,
Closing the issue based on comments above. If the issue still occurs or starts occuring again, please reopen it or (preferably) open new issue.

Best regards,
Wojciech

**Closed as completed by wzagrajcz** 2024-07-22 08:15 UTC
Labels: bug, planned, delivery

**Comment by landrew57** [comment] 2024-07-22 22:56
Thanks all for getting this resolved with the API fix.
