### ISSUE TITLE
Property version is not been update on the output

### ISSUE THREAD

**Issue by carnei-ro** [akamai/terraform-provider-akamai#208] opened 2021-01-21 19:29 UTC
### Expected Behavior
After modifying a property that was activated, it should create a new one and update the output "latest property"

### Actual Behavior
It creates a new property, but it does not change the "latest property" output. In the next terraform plan/apply the "latest property" output changes.

It was working in the past (provider < 1.0.0).
It is terrible because I can not "chain" an activation in staging on any change (it must run terraform plan/apply twice)

**Comment by carnei-ro** [comment] 2021-01-21 21:02
"known after apply" is not showing on "plan / apply"

**Comment by carnei-ro** [comment] 2021-03-16 13:17
just tested the provider version 1.3.1 and it still not working.

- create a property
- create an activation passing the `akamai_property.my-property.latest_version` to the activation parameter `version`

Run terraform apply
All works. Property created and activated.

Edit something about the property, run `terraform apply` again. We expect:
- changes at the property
- new activation

The actual behavior is:
- changes at the property

To activate the changes I have to run terraform one more time.

**Comment by ericrichtert** [comment] 2021-03-26 18:28
I have the same issue

**Comment by carnei-ro** [comment] 2021-03-26 18:30
@ericrichtert I'm using my own provider until fix. Try if you want: 
```hcl
terraform {
  required_providers {
    akamai = {
      # source = "akamai/akamai"
      source  = "carnei-ro/akamai"
      version = ">= 1.4.0"
    }
  }
}
```

The downsize is: the property version will be marked always as computed.... but, for me, it is ok.

**Comment by ericrichtert** [comment] 2021-03-26 18:39
I created a case at akamai and send an email to the development team

**Comment by siwyd** [comment] 2021-03-28 07:27
I can confirm the same behavior in the one Terraform repo that I upgraded > 1.0. All repo's that still use < 1.0 don't exhibit this behavior.

**Comment by lkowalsk-akamai-com** [comment] 2021-03-30 10:54
Hi, the issue should be fixed now in latest release (1.5.0). Please verify and close the ticket.

**Comment by ericrichtert** [comment] 2021-03-30 13:30
I can't test due to https://github.com/akamai/terraform-provider-akamai/issues/222

**Comment by carnei-ro** [comment] 2021-03-30 14:35
It seems to be working, although the need to delete and to reimport the property from the Terraform State is a real pain :-1:

**Comment by carnei-ro** [comment] 2021-03-30 17:20
It seems to be working... I have created a silly bash script (depends on `jq`) to workaround the changes at property hostnames;

I only have one `akamai_property` per state file and my certificates are `CPS_MANAGED`.

```bash
terraform state pull > terraform.tfstate

AKAMAI_PROPERTY=$(cat terraform.tfstate | jq -cr '.resources[] | select(.type == "akamai_property")')
REMOVED_PROPERTY=$(cat terraform.tfstate | jq -cr 'del(.resources[] | select(.type == "akamai_property"))')

idx=$(echo $REMOVED_PROPERTY | jq '.resources | length')

HOSTNAMES_TYPE=$(echo $AKAMAI_PROPERTY | jq -cr '.instances[0].attributes.hostnames | type')

if [ "array" == "${HOSTNAMES_TYPE}" ]; then
  echo "State seems to be ok. Exiting..."
  exit 0
fi

NEW_HOSTNAMES=$(echo $AKAMAI_PROPERTY | jq -cr '[ .instances[0].attributes.hostnames | to_entries[] | {"cname_to":.value, "cname_from":.key, "cert_provisioning_type":"CPS_MANAGED"} ]')

NEW_AKAMAI_PROPERTY=$(echo $AKAMAI_PROPERTY | jq -cr --argjson hostnames "$NEW_HOSTNAMES" '.instances[0].attributes.hostnames = $hostnames' )

echo $REMOVED_PROPERTY > file1
echo $NEW_AKAMAI_PROPERTY > file2

jq --argfile property file2 ".resources[$idx] = \$property" file1 > tmp
rm -f file1 file2
mv terraform.tfstate terraform.tfstate-original
jq '.serial += 1' tmp > terraform.tfstate
rm -f tmp

terraform state push terraform.tfstate
```

**Closed as completed** 2021-03-31 07:48 UTC
