### ISSUE TITLE
DXE-3098 panic: unaligned 64-bit atomic operation

### ISSUE THREAD

**Issue by desch64** [akamai/terraform-provider-akamai#470] opened 2023-09-06 11:57 UTC
### Terraform Version

Terraform v1.5.6
on windows_386

### Affected Resource(s)
Please list the resources as a list, for example:
- data "akamai_group"
- resource "akamai_networklist_network_list"
- data "akamai_contract"

### Debug Output

https://gist.github.com/desch64/d1610337b4afe50b5cc3406b4c9cd8a2

### Expected Behavior

Should see the standard output of terraform plan

### Actual Behavior

Planning fails

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. Crash

**Comment by dawiddzhafarov** [comment] 2023-09-06 12:23
Hi @desch64,

This is a known bug in a third-party library: https://github.com/allegro/bigcache/issues/368. 

With regards,
Dawid

**Comment by dawiddzhafarov** [comment] 2023-09-06 12:55
For the data sources "akamai_group" and "akamai_contract" this issue will not occur with upcoming release. We will work on removing the dependency in networklists resource.

**Comment by lkowalsk-akamai-com** [comment] 2023-11-09 15:16
Hi, this issues is caused by problem with bigcache library that is not working correctly on 32bits Windows machines. Please consider using different machine/os combination. We will close it for now and pottentialy get back to it once bigcache is updated.

**Closed as completed by lkowalsk-akamai-com** 2023-11-09 15:16 UTC
Labels: bug, delivery, STG
